/*

 ljve.io - Live Javascript Virtualized Environment
 Copyright (C) 2010-2014 Marco Minetti <marco.minetti@novetica.org>

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU Affero General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU Affero General Public License for more details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>.

 */

//O: Stores Javascript documentation objects generated by 'code_documentation' kernel preprocessor.
platform.development.jsdoc = platform.development.jsdoc || {};

//T: MISSING CODE DOCUMENTATION
platform.development.jsdoc._store = platform.development.jsdoc._store || {};

//T: MISSING CODE DOCUMENTATION
platform.development.jsdoc.export = function(path){
  platform.io.set.string(path,JSON.stringify(platform.development.jsdoc._store));
};