language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.5"
  - "3.0"
  - "3.3"
  - "4.0"
  - "4.1"
env:
  - CXX=g++-4.8
addons:
apt:
  sources:
  - ubuntu-toolchain-r-test
  packages:
  - gcc-4.8
  - g++-4.8