/*
 jQuery Migrate 1.2.1 | jquery.org | (c) 2005-2012 jQuery Foundation, Inc. | MIT */
void 0===jQuery.migrateMute&&(jQuery.migrateMute=!0);
(function(a,m,k){function f(b){var c=m.console;p[b]||(p[b]=!0,a.migrateWarnings.push(b),c&&c.warn&&!a.migrateMute&&(c.warn("JQMIGRATE: "+b),a.migrateTrace&&c.trace&&c.trace()))}function q(b,c,d,e){if(Object.defineProperty)try{return Object.defineProperty(b,c,{configurable:!0,enumerable:!0,get:function(){return f(e),d},set:function(a){f(e);d=a}}),k}catch(h){}a._definePropertyBroken=!0;b[c]=d}var p={};a.migrateWarnings=[];!a.migrateMute&&m.console&&m.console.log&&m.console.log("JQMIGRATE: Logging is active");
a.migrateTrace===k&&(a.migrateTrace=!0);a.migrateReset=function(){p={};a.migrateWarnings.length=0};"BackCompat"===document.compatMode&&f("jQuery is not compatible with Quirks Mode");var r=a("<input/>",{size:1}).attr("size")&&a.attrFn,s=a.attr,z=a.attrHooks.value&&a.attrHooks.value.get||function(){return null},A=a.attrHooks.value&&a.attrHooks.value.set||function(){return k},B=/^(?:input|button)$/i,C=/^[238]$/,D=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,
E=/^(?:checked|selected)$/i;q(a,"attrFn",r||{},"jQuery.attrFn is deprecated");a.attr=function(b,c,d,e){var h=c.toLowerCase(),g=b&&b.nodeType;return e&&(4>s.length&&f("jQuery.fn.attr( props, pass ) is deprecated"),b&&!C.test(g)&&(r?c in r:a.isFunction(a.fn[c])))?a(b)[c](d):("type"===c&&d!==k&&B.test(b.nodeName)&&b.parentNode&&f("Can't change the 'type' of an input or button in IE 6/7/8"),!a.attrHooks[h]&&D.test(h)&&(a.attrHooks[h]={get:function(b,c){var d,e=a.prop(b,c);return!0===e||"boolean"!=typeof e&&
(d=b.getAttributeNode(c))&&!1!==d.nodeValue?c.toLowerCase():k},set:function(b,c,d){var e;return!1===c?a.removeAttr(b,d):(e=a.propFix[d]||d,e in b&&(b[e]=!0),b.setAttribute(d,d.toLowerCase())),d}},E.test(h)&&f("jQuery.fn.attr('"+h+"') may use property instead of attribute")),s.call(a,b,c,d))};a.attrHooks.value={get:function(b,a){var d=(b.nodeName||"").toLowerCase();return"button"===d?z.apply(this,arguments):("input"!==d&&"option"!==d&&f("jQuery.fn.attr('value') no longer gets properties"),a in b?b.value:
null)},set:function(a,c){var d=(a.nodeName||"").toLowerCase();return"button"===d?A.apply(this,arguments):("input"!==d&&"option"!==d&&f("jQuery.fn.attr('value', val) no longer sets properties"),a.value=c,k)}};var n,g,t=a.fn.init,F=a.parseJSON,G=/^([^<]*)(<[\w\W]+>)([^>]*)$/;a.fn.init=function(b,c,d){var e;return b&&"string"==typeof b&&!a.isPlainObject(c)&&(e=G.exec(a.trim(b)))&&e[0]&&("<"!==b.charAt(0)&&f("$(html) HTML strings must start with '<' character"),e[3]&&f("$(html) HTML text after last tag is ignored"),
"#"===e[0].charAt(0)&&(f("HTML string cannot start with a '#' character"),a.error("JQMIGRATE: Invalid selector string (XSS)")),c&&c.context&&(c=c.context),a.parseHTML)?t.call(this,a.parseHTML(e[2],c,!0),c,d):t.apply(this,arguments)};a.fn.init.prototype=a.fn;a.parseJSON=function(a){return a||null===a?F.apply(this,arguments):(f("jQuery.parseJSON requires a valid JSON string"),null)};a.uaMatch=function(a){a=a.toLowerCase();a=/(chrome)[ \/]([\w.]+)/.exec(a)||/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(a)||
/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}};a.browser||(n=a.uaMatch(navigator.userAgent),g={},n.browser&&(g[n.browser]=!0,g.version=n.version),g.chrome?g.webkit=!0:g.webkit&&(g.safari=!0),a.browser=g);q(a,"browser",a.browser,"jQuery.browser is deprecated");a.sub=function(){function b(a,c){return new b.fn.init(a,c)}a.extend(!0,b,this);b.superclass=this;b.fn=b.prototype=this();b.fn.constructor=b;b.sub=
this.sub;b.fn.init=function(d,e){return e&&e instanceof a&&!(e instanceof b)&&(e=b(e)),a.fn.init.call(this,d,e,c)};b.fn.init.prototype=b.fn;var c=b(document);return f("jQuery.sub() is deprecated"),b};a.ajaxSetup({converters:{"text json":a.parseJSON}});var H=a.fn.data;a.fn.data=function(b){var c,d,e=this[0];return!e||"events"!==b||1!==arguments.length||(c=a.data(e,b),d=a._data(e,b),c!==k&&c!==d||d===k)?H.apply(this,arguments):(f("Use of jQuery.fn.data('events') is deprecated"),d)};var I=/\/(java|ecma)script/i,
J=a.fn.andSelf||a.fn.addBack;a.fn.andSelf=function(){return f("jQuery.fn.andSelf() replaced by jQuery.fn.addBack()"),J.apply(this,arguments)};a.clean||(a.clean=function(b,c,d,e){c=c||document;c=!c.nodeType&&c[0]||c;c=c.ownerDocument||c;f("jQuery.clean() is deprecated");var h,g,l=[];if(a.merge(l,a.buildFragment(b,c).childNodes),d){h=function(a){return!a.type||I.test(a.type)?e?e.push(a.parentNode?a.parentNode.removeChild(a):a):d.appendChild(a):k};for(b=0;null!=(c=l[b]);b++)a.nodeName(c,"script")&&h(c)||
(d.appendChild(c),c.getElementsByTagName!==k&&(g=a.grep(a.merge([],c.getElementsByTagName("script")),h),l.splice.apply(l,[b+1,0].concat(g)),b+=g.length))}return l});var K=a.event.add,L=a.event.remove,M=a.event.trigger,N=a.fn.toggle,u=a.fn.live,v=a.fn.die,w=/\b(?:ajaxStart|ajaxStop|ajaxSend|ajaxComplete|ajaxError|ajaxSuccess)\b/,x=/(?:^|\s)hover(\.\S+|)\b/,y=function(b){return"string"!=typeof b||a.event.special.hover?b:(x.test(b)&&f("'hover' pseudo-event is deprecated, use 'mouseenter mouseleave'"),
b&&b.replace(x,"mouseenter$1 mouseleave$1"))};a.event.props&&"attrChange"!==a.event.props[0]&&a.event.props.unshift("attrChange","attrName","relatedNode","srcElement");a.event.dispatch&&q(a.event,"handle",a.event.dispatch,"jQuery.event.handle is undocumented and deprecated");a.event.add=function(a,c,d,e,h){a!==document&&w.test(c)&&f("AJAX events should be attached to document: "+c);K.call(this,a,y(c||""),d,e,h)};a.event.remove=function(a,c,d,e,f){L.call(this,a,y(c)||"",d,e,f)};a.fn.error=function(){var a=
Array.prototype.slice.call(arguments,0);return f("jQuery.fn.error() is deprecated"),a.splice(0,0,"error"),arguments.length?this.bind.apply(this,a):(this.triggerHandler.apply(this,a),this)};a.fn.toggle=function(b,c){if(!a.isFunction(b)||!a.isFunction(c))return N.apply(this,arguments);f("jQuery.fn.toggle(handler, handler...) is deprecated");var d=arguments,e=b.guid||a.guid++,h=0,g=function(c){var e=(a._data(this,"lastToggle"+b.guid)||0)%h;return a._data(this,"lastToggle"+b.guid,e+1),c.preventDefault(),
d[e].apply(this,arguments)||!1};for(g.guid=e;d.length>h;)d[h++].guid=e;return this.click(g)};a.fn.live=function(b,c,d){return f("jQuery.fn.live() is deprecated"),u?u.apply(this,arguments):(a(this.context).on(b,this.selector,c,d),this)};a.fn.die=function(b,c){return f("jQuery.fn.die() is deprecated"),v?v.apply(this,arguments):(a(this.context).off(b,this.selector||"**",c),this)};a.event.trigger=function(a,c,d,e){return d||w.test(a)||f("Global events are undocumented and deprecated"),M.call(this,a,c,
d||document,e)};a.each("ajaxStart ajaxStop ajaxSend ajaxComplete ajaxError ajaxSuccess".split(" "),function(b,c){a.event.special[c]={setup:function(){var b=this;return b!==document&&(a.event.add(document,c+"."+a.guid,function(){a.event.trigger(c,null,b,!0)}),a._data(this,c,a.guid++)),!1},teardown:function(){return this!==document&&a.event.remove(document,c+"."+a._data(this,c)),!1}}})})(jQuery,window);
